### ISSUE TITLE
spatne zvyrazneni syntaxe

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [Michal-Mikolas/Nette-package-for-Sublime-Text-2#1]
`
{block content}
    {foreach $database->table('projects') as $project}
        <h2><a href="#" target="_blank">{$project->aaaa}</a> - <a href="#">eee</a></h2>
    {/foreach}
{/block}
`
u {$project->aaaa} se to rozbije viz screenshoty http://imageshack.us/g/442/screenshot20120211at104.png/

**Comment by Michal-Mikolas** [comment]
díky za report, opraveno
