### ISSUE TITLE
podpora zencoding pro *.latte

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [Michal-Mikolas/Nette-package-for-Sublime-Text-2#3]
v souborech s koncovkou *latte (a hroma dalsich) nefunguje zencoding
doted jsem si myslel ze tohle se musi nastavovat primo nekde v zencoding (kde jsem to nenasel) ale ted jsem stahl plugin pro stylus https://github.com/LearnBoost/stylus/blob/master/editors/Stylus.tmbundle/Syntaxes/Stylus.tmLanguage a vnem zencoding funguje.  myslis ze bys mohl mrknout jestli tam neni neco co by tohle vysvetlovalo. diky

**Comment by Michal-Mikolas** [comment]
Ahoj, tak jsem to zkoušel. Nainstaloval jsem Stylus package, otevírám .styl soubor z examples, mačkám CTRL+ALT+ENTER (vyvolání Zen Codingu), a nic se neděje. U mě to tedy nefunguje. Nebo jsem udělal něco jinak, než ty?

**Comment by 890f2151c2be69c51db72017546d00fd** [comment]
koukni na obrazek http://imageshack.us/photo/my-images/839/screenshot20120314at121.png/ ve stylus kdyz normalne pisi tak mi to automaticky ukazuje vysledek a staci dat enter nebo tab. ve standardnim html uz se mi to preview neukazuje a funguje pouze tab a v .latte nefunguje ani ten tab.  
kombinace ctrl+alt+enter mi funguje pouze v html v latte ani stylus to "konzoli" nevyvola.

**Comment by Michal-Mikolas** [comment]
Tak jsem na to konečně přišel, Stylus má v Zen codingu speciální podporu: 
- https://bitbucket.org/sublimator/sublime-2-zencoding/src/8be235edaf1c/zencoding/filters/stylus.py
- https://bitbucket.org/sublimator/sublime-2-zencoding/src/8be235edaf1c/zencoding/interface/editor.py#cl-194
- https://bitbucket.org/sublimator/sublime-2-zencoding/src/8be235edaf1c/sublimezenplugin.py#cl-48

**Comment by tomasnikl** [comment]
Bohuzel uz ani jeden z odkazu na bitbucket nefunguje :(
